use once_cell::sync::Lazy;

struct Color {
    name: &'static str, // Changed from String to &'static str,
    r: f32,
    g: f32,
    b: f32,
}

/// Colors from Pymol
///
/// Statically defining all of Pymols's named colors [from Color.cpp](https://github.com/schrodinger/pymol-open-source/blob/master/layer1/Color.cpp).
///
pub static COLOR_SET: Lazy<[Color; 154]> = Lazy::new(|| {
    [
        Color {
            name: "white",
            r: 1.0,
            g: 1.0,
            b: 1.0,
        },
        Color {
            name: "black",
            r: 0.0,
            g: 0.0,
            b: 0.0,
        },
        Color {
            name: "blue",
            r: 0.0,
            g: 0.0,
            b: 1.0,
        },
        Color {
            name: "green",
            r: 0.0,
            g: 1.0,
            b: 0.0,
        },
        Color {
            name: "red",
            r: 1.0,
            g: 0.0,
            b: 0.0,
        },
        Color {
            name: "cyan",
            r: 0.0,
            g: 1.0,
            b: 1.0,
        },
        Color {
            name: "yellow",
            r: 1.0,
            g: 1.0,
            b: 0.0,
        },
        Color {
            name: "dash",
            r: 1.0,
            g: 1.0,
            b: 0.0,
        },
        Color {
            name: "magenta",
            r: 1.0,
            g: 0.0,
            b: 1.0,
        },
        Color {
            name: "salmon",
            r: 1.0,
            g: 0.6,
            b: 0.6,
        },
        Color {
            name: "lime",
            r: 0.5,
            g: 1.0,
            b: 0.5,
        },
        Color {
            name: "slate",
            r: 0.5,
            g: 0.5,
            b: 1.0,
        },
        Color {
            name: "hotpink",
            r: 1.0,
            g: 0.0,
            b: 0.5,
        },
        Color {
            name: "orange",
            r: 1.0,
            g: 0.5,
            b: 0.0,
        },
        Color {
            name: "chartreuse",
            r: 0.5,
            g: 1.0,
            b: 0.0,
        },
        Color {
            name: "limegreen",
            r: 0.0,
            g: 1.0,
            b: 0.5,
        },
        Color {
            name: "purpleblue",
            r: 0.5,
            g: 0.0,
            b: 1.0,
        },
        Color {
            name: "marine",
            r: 0.0,
            g: 0.5,
            b: 1.0,
        },
        Color {
            name: "olive",
            r: 0.77,
            g: 0.7,
            b: 0.0,
        },
        Color {
            name: "purple",
            r: 0.75,
            g: 0.0,
            b: 0.75,
        },
        Color {
            name: "teal",
            r: 0.0,
            g: 0.75,
            b: 0.75,
        },
        Color {
            name: "ruby",
            r: 0.6,
            g: 0.2,
            b: 0.2,
        },
        Color {
            name: "forest",
            r: 0.2,
            g: 0.6,
            b: 0.2,
        },
        Color {
            name: "deepblue",
            r: 0.25,
            g: 0.25,
            b: 0.65,
        },
        Color {
            name: "grey",
            r: 0.5,
            g: 0.5,
            b: 0.5,
        },
        Color {
            name: "gray",
            r: 0.5,
            g: 0.5,
            b: 0.5,
        },
        Color {
            name: "carbon",
            r: 0.2,
            g: 1.0,
            b: 0.2,
        },
        Color {
            name: "nitrogen",
            r: 0.2,
            g: 0.2,
            b: 1.0,
        },
        Color {
            name: "oxygen",
            r: 1.0,
            g: 0.3,
            b: 0.3,
        },
        Color {
            name: "hydrogen",
            r: 0.9,
            g: 0.9,
            b: 0.9,
        },
        Color {
            name: "brightorange",
            r: 1.0,
            g: 0.7,
            b: 0.2,
        },
        Color {
            name: "sulfur",
            r: 0.9,
            g: 0.775,
            b: 0.25,
        },
        Color {
            name: "tv_red",
            r: 1.0,
            g: 0.2,
            b: 0.2,
        },
        Color {
            name: "tv_green",
            r: 0.2,
            g: 1.0,
            b: 0.2,
        },
        Color {
            name: "tv_blue",
            r: 0.3,
            g: 0.3,
            b: 1.0,
        },
        Color {
            name: "tv_yellow",
            r: 1.0,
            g: 1.0,
            b: 0.2,
        },
        Color {
            name: "yelloworange",
            r: 1.0,
            g: 0.87,
            b: 0.37,
        },
        Color {
            name: "tv_orange",
            r: 1.0,
            g: 0.55,
            b: 0.15,
        },
        Color {
            name: "br0",
            r: 0.1,
            g: 0.1,
            b: 1.0,
        },
        Color {
            name: "br1",
            r: 0.2,
            g: 0.1,
            b: 0.9,
        },
        Color {
            name: "br2",
            r: 0.3,
            g: 0.1,
            b: 0.8,
        },
        Color {
            name: "br3",
            r: 0.4,
            g: 0.1,
            b: 0.7,
        },
        Color {
            name: "br4",
            r: 0.5,
            g: 0.1,
            b: 0.6,
        },
        Color {
            name: "br5",
            r: 0.6,
            g: 0.1,
            b: 0.5,
        },
        Color {
            name: "br6",
            r: 0.7,
            g: 0.1,
            b: 0.4,
        },
        Color {
            name: "br7",
            r: 0.8,
            g: 0.1,
            b: 0.3,
        },
        Color {
            name: "br8",
            r: 0.9,
            g: 0.1,
            b: 0.2,
        },
        Color {
            name: "br9",
            r: 1.0,
            g: 0.1,
            b: 0.1,
        },
        Color {
            name: "pink",
            r: 1.0,
            g: 0.65,
            b: 0.85,
        },
        Color {
            name: "firebrick",
            r: 0.698,
            g: 0.13,
            b: 0.13,
        },
        Color {
            name: "chocolate",
            r: 0.555,
            g: 0.222,
            b: 0.111,
        },
        Color {
            name: "brown",
            r: 0.65,
            g: 0.32,
            b: 0.17,
        },
        Color {
            name: "wheat",
            r: 0.99,
            g: 0.82,
            b: 0.65,
        },
        Color {
            name: "violet",
            r: 1.0,
            g: 0.5,
            b: 1.0,
        },
        Color {
            name: "grey00",
            r: 0.0,
            g: 0.0,
            b: 0.0,
        },
        Color {
            name: "grey01",
            r: 0.01,
            g: 0.01,
            b: 0.01,
        },
        Color {
            name: "grey02",
            r: 0.02,
            g: 0.02,
            b: 0.02,
        },
        Color {
            name: "grey03",
            r: 0.03,
            g: 0.03,
            b: 0.03,
        },
        Color {
            name: "grey04",
            r: 0.04,
            g: 0.04,
            b: 0.04,
        },
        Color {
            name: "grey05",
            r: 0.05,
            g: 0.05,
            b: 0.05,
        },
        Color {
            name: "grey06",
            r: 0.06,
            g: 0.06,
            b: 0.06,
        },
        Color {
            name: "grey07",
            r: 0.07,
            g: 0.07,
            b: 0.07,
        },
        Color {
            name: "grey08",
            r: 0.08,
            g: 0.08,
            b: 0.08,
        },
        Color {
            name: "grey09",
            r: 0.09,
            g: 0.09,
            b: 0.09,
        },
        Color {
            name: "grey10",
            r: 0.10,
            g: 0.10,
            b: 0.10,
        },
        Color {
            name: "grey11",
            r: 0.11,
            g: 0.11,
            b: 0.11,
        },
        Color {
            name: "grey12",
            r: 0.12,
            g: 0.12,
            b: 0.12,
        },
        Color {
            name: "grey13",
            r: 0.13,
            g: 0.13,
            b: 0.13,
        },
        Color {
            name: "grey14",
            r: 0.14,
            g: 0.14,
            b: 0.14,
        },
        Color {
            name: "grey15",
            r: 0.15,
            g: 0.15,
            b: 0.15,
        },
        Color {
            name: "grey16",
            r: 0.16,
            g: 0.16,
            b: 0.16,
        },
        Color {
            name: "grey17",
            r: 0.17,
            g: 0.17,
            b: 0.17,
        },
        Color {
            name: "grey18",
            r: 0.18,
            g: 0.18,
            b: 0.18,
        },
        Color {
            name: "grey19",
            r: 0.19,
            g: 0.19,
            b: 0.19,
        },
        Color {
            name: "grey20",
            r: 0.20,
            g: 0.20,
            b: 0.20,
        },
        Color {
            name: "grey21",
            r: 0.21,
            g: 0.21,
            b: 0.21,
        },
        Color {
            name: "grey22",
            r: 0.22,
            g: 0.22,
            b: 0.22,
        },
        Color {
            name: "grey23",
            r: 0.23,
            g: 0.23,
            b: 0.23,
        },
        Color {
            name: "grey24",
            r: 0.24,
            g: 0.24,
            b: 0.24,
        },
        Color {
            name: "grey25",
            r: 0.25,
            g: 0.25,
            b: 0.25,
        },
        Color {
            name: "grey26",
            r: 0.26,
            g: 0.26,
            b: 0.26,
        },
        Color {
            name: "grey27",
            r: 0.27,
            g: 0.27,
            b: 0.27,
        },
        Color {
            name: "grey28",
            r: 0.28,
            g: 0.28,
            b: 0.28,
        },
        Color {
            name: "grey29",
            r: 0.29,
            g: 0.29,
            b: 0.29,
        },
        Color {
            name: "grey30",
            r: 0.30,
            g: 0.30,
            b: 0.30,
        },
        Color {
            name: "grey31",
            r: 0.31,
            g: 0.31,
            b: 0.31,
        },
        Color {
            name: "grey32",
            r: 0.32,
            g: 0.32,
            b: 0.32,
        },
        Color {
            name: "grey33",
            r: 0.33,
            g: 0.33,
            b: 0.33,
        },
        Color {
            name: "grey34",
            r: 0.34,
            g: 0.34,
            b: 0.34,
        },
        Color {
            name: "grey35",
            r: 0.35,
            g: 0.35,
            b: 0.35,
        },
        Color {
            name: "grey36",
            r: 0.36,
            g: 0.36,
            b: 0.36,
        },
        Color {
            name: "grey37",
            r: 0.37,
            g: 0.37,
            b: 0.37,
        },
        Color {
            name: "grey38",
            r: 0.38,
            g: 0.38,
            b: 0.38,
        },
        Color {
            name: "grey39",
            r: 0.39,
            g: 0.39,
            b: 0.39,
        },
        Color {
            name: "grey40",
            r: 0.40,
            g: 0.40,
            b: 0.40,
        },
        Color {
            name: "grey41",
            r: 0.41,
            g: 0.41,
            b: 0.41,
        },
        Color {
            name: "grey42",
            r: 0.42,
            g: 0.42,
            b: 0.42,
        },
        Color {
            name: "grey43",
            r: 0.43,
            g: 0.43,
            b: 0.43,
        },
        Color {
            name: "grey44",
            r: 0.44,
            g: 0.44,
            b: 0.44,
        },
        Color {
            name: "grey45",
            r: 0.45,
            g: 0.45,
            b: 0.45,
        },
        Color {
            name: "grey46",
            r: 0.46,
            g: 0.46,
            b: 0.46,
        },
        Color {
            name: "grey47",
            r: 0.47,
            g: 0.47,
            b: 0.47,
        },
        Color {
            name: "grey48",
            r: 0.48,
            g: 0.48,
            b: 0.48,
        },
        Color {
            name: "grey49",
            r: 0.49,
            g: 0.49,
            b: 0.49,
        },
        Color {
            name: "grey50",
            r: 0.50,
            g: 0.50,
            b: 0.50,
        },
        Color {
            name: "grey51",
            r: 0.51,
            g: 0.51,
            b: 0.51,
        },
        Color {
            name: "grey52",
            r: 0.52,
            g: 0.52,
            b: 0.52,
        },
        Color {
            name: "grey53",
            r: 0.53,
            g: 0.53,
            b: 0.53,
        },
        Color {
            name: "grey54",
            r: 0.54,
            g: 0.54,
            b: 0.54,
        },
        Color {
            name: "grey55",
            r: 0.55,
            g: 0.55,
            b: 0.55,
        },
        Color {
            name: "grey56",
            r: 0.56,
            g: 0.56,
            b: 0.56,
        },
        Color {
            name: "grey57",
            r: 0.57,
            g: 0.57,
            b: 0.57,
        },
        Color {
            name: "grey58",
            r: 0.58,
            g: 0.58,
            b: 0.58,
        },
        Color {
            name: "grey59",
            r: 0.59,
            g: 0.59,
            b: 0.59,
        },
        Color {
            name: "grey60",
            r: 0.60,
            g: 0.60,
            b: 0.60,
        },
        Color {
            name: "grey61",
            r: 0.61,
            g: 0.61,
            b: 0.61,
        },
        Color {
            name: "grey62",
            r: 0.62,
            g: 0.62,
            b: 0.62,
        },
        Color {
            name: "grey63",
            r: 0.63,
            g: 0.63,
            b: 0.63,
        },
        Color {
            name: "grey64",
            r: 0.64,
            g: 0.64,
            b: 0.64,
        },
        Color {
            name: "grey65",
            r: 0.65,
            g: 0.65,
            b: 0.65,
        },
        Color {
            name: "grey66",
            r: 0.66,
            g: 0.66,
            b: 0.66,
        },
        Color {
            name: "grey67",
            r: 0.67,
            g: 0.67,
            b: 0.67,
        },
        Color {
            name: "grey68",
            r: 0.68,
            g: 0.68,
            b: 0.68,
        },
        Color {
            name: "grey69",
            r: 0.69,
            g: 0.69,
            b: 0.69,
        },
        Color {
            name: "grey70",
            r: 0.70,
            g: 0.70,
            b: 0.70,
        },
        Color {
            name: "grey71",
            r: 0.71,
            g: 0.71,
            b: 0.71,
        },
        Color {
            name: "grey72",
            r: 0.72,
            g: 0.72,
            b: 0.72,
        },
        Color {
            name: "grey73",
            r: 0.73,
            g: 0.73,
            b: 0.73,
        },
        Color {
            name: "grey74",
            r: 0.74,
            g: 0.74,
            b: 0.74,
        },
        Color {
            name: "grey75",
            r: 0.75,
            g: 0.75,
            b: 0.75,
        },
        Color {
            name: "grey76",
            r: 0.76,
            g: 0.76,
            b: 0.76,
        },
        Color {
            name: "grey77",
            r: 0.77,
            g: 0.77,
            b: 0.77,
        },
        Color {
            name: "grey78",
            r: 0.78,
            g: 0.78,
            b: 0.78,
        },
        Color {
            name: "grey79",
            r: 0.79,
            g: 0.79,
            b: 0.79,
        },
        Color {
            name: "grey80",
            r: 0.80,
            g: 0.80,
            b: 0.80,
        },
        Color {
            name: "grey81",
            r: 0.81,
            g: 0.81,
            b: 0.81,
        },
        Color {
            name: "grey82",
            r: 0.82,
            g: 0.82,
            b: 0.82,
        },
        Color {
            name: "grey83",
            r: 0.83,
            g: 0.83,
            b: 0.83,
        },
        Color {
            name: "grey84",
            r: 0.84,
            g: 0.84,
            b: 0.84,
        },
        Color {
            name: "grey85",
            r: 0.85,
            g: 0.85,
            b: 0.85,
        },
        Color {
            name: "grey86",
            r: 0.86,
            g: 0.86,
            b: 0.86,
        },
        Color {
            name: "grey87",
            r: 0.87,
            g: 0.87,
            b: 0.87,
        },
        Color {
            name: "grey88",
            r: 0.88,
            g: 0.88,
            b: 0.88,
        },
        Color {
            name: "grey89",
            r: 0.89,
            g: 0.89,
            b: 0.89,
        },
        Color {
            name: "grey90",
            r: 0.90,
            g: 0.90,
            b: 0.90,
        },
        Color {
            name: "grey91",
            r: 0.91,
            g: 0.91,
            b: 0.91,
        },
        Color {
            name: "grey92",
            r: 0.92,
            g: 0.92,
            b: 0.92,
        },
        Color {
            name: "grey93",
            r: 0.93,
            g: 0.93,
            b: 0.93,
        },
        Color {
            name: "grey94",
            r: 0.94,
            g: 0.94,
            b: 0.94,
        },
        Color {
            name: "grey95",
            r: 0.95,
            g: 0.95,
            b: 0.95,
        },
        Color {
            name: "grey96",
            r: 0.96,
            g: 0.96,
            b: 0.96,
        },
        Color {
            name: "grey97",
            r: 0.97,
            g: 0.97,
            b: 0.97,
        },
        Color {
            name: "grey98",
            r: 0.98,
            g: 0.98,
            b: 0.98,
        },
        Color {
            name: "grey99",
            r: 0.99,
            g: 0.99,
            b: 0.99,
        },
    ]
});

#[test]
fn test_first_color_name() {
    assert_eq!(COLOR_SET[0].name, "white");
    assert_eq!(COLOR_SET[20].name, "teal");
    assert_eq!(COLOR_SET[53].name, "violet");
    assert_eq!(COLOR_SET[54].name, "grey00");
    assert_eq!(COLOR_SET[153].name, "grey99");
}
