project:
  type: website
  resources:
    - "examples/**"
    - "doc/**"

website:
  title: "pseutils"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: examples.qmd
        text: Examples
      - href: doc/pseutils/index.html
        text: RustDoc
    right:
      - icon: github
        href: https://github.com/zachcp/pseutils
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
